### ISSUE TITLE
output image is gray and all 0

### ISSUE THREAD

**Issue by CindiLab-WSU** [fsemerar/segment-anything-gui#1]
I can run the code as instructed. However, the output annotated file is not exported appropriately.

**Comment by Ka0Ri** [comment]
The output is acutally saved with mask labels, simple snipset to get image:

```Python
import cv2
import matplotlib.pyplot as plt

tag = cv2.imread('tag.jpg', 0)
plt.imshow(tag)
plt.savefig('tag_heat.jpg')
plt.show()
```
